### ISSUE TITLE
problem whit leonardo board

### ISSUE THREAD

**Issue by Nasty76** [RamjetX/Logitech-G25-27-Shifter#1]
Hello i just try to get that work and , i get that work allmost , 
my h shifter position start number 2 and red buttons not work in windows , debug show buttons are read in shift register correctly , any idea what is wrong.
H mode shifter work and up down shift work , but not buttons :(
hat switch work and 2 of up black buttons..
example h shifter mode gear 1 is windows usb game control button 2 etc , up down shift is 9 and 10.

**Comment by Nasty76** [comment]
i today debug my problem after good sleeped night and i find bug for set gear loop.
Joystick.setButton 0 is first game controller button and gear return 0 when no gear select so when for loop start 0 that map that neutral position in button 1 in windows game controller , i knifed the code and make switch which map gear 1 to Joystick.setButton0 and gears work like thinked , still not looked button problem but i think switch construct fix that too

**Comment by Nasty76** [comment]
ok i debug button problem and same bug , u forget that gear and button bank is diferent variable , so gears start 0 and buttons start 0 not 11 like code but i fix now button section using next code:
  // Get the rest of the buttons from the shifter. Last button for gears is 9... so start at 10.
  int y = 0; 
  for (int i = 9; i <= 20; i++) { // get the button values from 4 to 12. Note, G25 Buttons 0-3 are not physical buttons you can use, they are either Missing from the board or Reverse mode and Sequential switch. Not mapped to the game since you don't really have control over them.
  
  y = i -5;
    Joystick.setButton(i,G25.getButton(y));
  }

**Comment by Nasty76** [comment]
here is working sketch to g25 shifter and g25 pedals in analog pin A2,A3,A4
pedals is 16bit mode.

/*
   The RamjetX G25 Shifter Library for Arduino Leonardo 32u4

   This project has used base code from http://www.isrtv.com/forums/topic/13189-diy-g25-shifter-interface-with-h-pattern-sequential-and-handbrake-modes/

   My work was simply to adapt and create the arduino library interface so that it was useable and configuarble with the
   Arduino environment.

   Alot of work when into creating a usable library and whilst I don't claim to have originally written the capture and
   decode work. Being a simple Bit-Shift register for the buttons and two Analog sticks for the shift gates, it did seem
   pointless to rewrite it as I'd essentially have written something very similar anyway.

   With that said, do pop by the link above and give the original author a big thanks for compiling and releasing his findings too.
   I have YouTube and forum place where I do embedded systems and simulation work also. Feel free to visit, say hi, and jump in a game
   with us.

   Find me at:
   https://www.youtube.com/channel/UCnJO2Gx_moUTu8oA-fNJXMA
   and if you'd like to contact me... RamjetX in discord. Find me lurking around the OZNZ or Simhub Discord channels

   Enjoy the Library. It is work in progress and subtle changes will likely occur to enhance functionality over time.

   RamjetX
*/

// RamjetX G25Shifter Library
#include <G25Shifter.h>
// RamjetX 16bit Joystick Pluggable HID Library for 1.6.6 IDE+
#include <Joystick.h>

/*
   Instructions:-

   Connect the G25 Shifter by calling the G25Shifter Library and giving it a name.

   Below I called my G25Shifter, simply G25... and it is referred to as G25 when you asking it to do stuff.

   The constructor wants you to enter the pins used for the following pins
   
   G25Shifter(int shifter_x, int shifter_y, int data_input_pin, int data_latch_pin, int data_clock_pin, int led1_pin)
*/

// Create Object G25
G25Shifter G25(A0, A1, 14, 16, 15, 3); // These are the pins I've decided to use on my board... you may change these to your liking

Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, JOYSTICK_TYPE_GAMEPAD,
                   32, 0,                  // Button Count, Hat Switch Count
                   true, true, true,     // X and Y, but no Z Axis
                   false, false, false,   // No Rx, Ry, or Rz
                   false, true,          // No rudder or throttle
                   false, true, false);  // No accelerator, brake, or steering

int throttlepin = A3;
int brakepin = A2;
int clutchpin = 04;

void setup() {
  Joystick.begin();
//Serial.begin(9600); // You can use this with the debug routine below to see the live data from the shifter
}


/*Main Program loop*/
void loop() {




// pedals section of g25 pedals analog inputs A0 , A1 and A2

Joystick.setThrottle(analogRead(throttlepin));
Joystick.setBrake(analogRead(brakepin));
Joystick.setZAxis(analogRead(clutchpin));
  //Shifter is ready to update and get information from. Remember to update atleast once before checking the information received from it.
  G25.update();

  // Puts the Gear Selected into Button 1-7 for Gear 1,2,3,4,5,6,R. All lower bank are OFF in Neutral.
  int gear = G25.getGear();

  /*
  // Loop through all of the gear buttons. 
  // Set every button to zero that does not match the currently selected gear. 
  // Neutral is 0. Gears 1 to 6, 7 is reverse and sequential shift up is 8 - and shift down is 9
  // 
  */

switch (gear) {
  case 1:
    Joystick.setButton(0, 1);
    break;
  case 2:
    Joystick.setButton(1, 1);
    break;
    case 3:
    Joystick.setButton(2, 1);
    break;
   case 4:
    Joystick.setButton(3, 1);
    break;
    case 5:
    Joystick.setButton(4, 1);
    break;
       case 6:
    Joystick.setButton(5, 1);
    break;
      case 7:
    Joystick.setButton(6, 1);
    break;
       case 8:
    Joystick.setButton(7, 1);
    break;
       case 9:
    Joystick.setButton(8, 1);
    break;
  default:
    // if nothing else matches, do the default
  for (int i = 0; i <9; i++)
  {Joystick.setButton(i,0);
  }
    break;
  }


  // Get the rest of the buttons from the shifter. Last button for gears is 9... so start at 10.
  int y = 0; 
  for (int i = 9; i <= 20; i++) { // get the button values from 4 to 12. Note, G25 Buttons 0-3 are not physical buttons you can use, they are either Missing from the board or Reverse mode and Sequential switch. Not mapped to the game since you don't really have control over them.
  
  y = i -5;
    Joystick.setButton(i,G25.getButton(y));
  }

// G25.print();    // Uncomment this if you want to print the serial debug information to the serial port. It's good for checking the X/Y values of the stick to tune the gate values if you have a dodgy stick.

  delay(10); // small delay just slows the refresh rate to help with flooding the PC with updates that aren't needed in a hurry from a shifter.

}// end loop

**Comment by Nasty76** [comment]
thanks for awesome g25 shifter library . that is nice

**Comment by Nasty76** [comment]
ok next problem was up down shift mode messing around , that add more gears if u are near given up or down shift value 
so i knifed ur awesome code again :|

if (buttons_Value_Array[DI_MODE] == 1)       // H-shifter mode? 0 = H-Shifter. 1 = Sequential Shifter
    if (shifterMode == SHIFTER_MODE)          // Shifter mode or in Handbrake Mode
    {
	if(shifter_y_Value >370 && shifter_y_Value <480)
	{centermode = 1;
	}
	
	if(shifter_y_Value > SS_UPSHIFT_BEGIN  && centermode == 1)
	{
centermode = 0;
gear = 8;

	}

if(shifter_y_Value < SS_DOWNSHIFT_BEGIN  && centermode == 1)
	{
centermode = 0;
gear = 9;

	}

	
    
	return gear;
}// end getSeqShifter
}
if (buttons_Value_Array[DI_MODE] == 1)       // H-shifter mode? 0 = H-Shifter. 1 = Sequential Shifter
    if (shifterMode == SHIFTER_MODE)          // Shifter mode or in Handbrake Mode
    {
	if(shifter_y_Value >370 && shifter_y_Value <480)
	{centermode = 1;
	}
	
	if(shifter_y_Value > SS_UPSHIFT_BEGIN  && centermode == 1)
	{
centermode = 0;
gear = 8;

	}

if(shifter_y_Value < SS_DOWNSHIFT_BEGIN  && centermode == 1)
	{
centermode = 0;
gear = 9;

	}

	
    
	return gear;
}// end getSeqShifter
}
i add there var center mode which activate when shifter stick go center after shifting happening , ok this broke ur awesome debug windows but , in game no more miss shift .
if u want u can freely use my code if u want.

**Comment by RamjetX** [comment]
Hi Nasty76... great work and very much appreciated that you've taken such a close look at it.

In all fairness, I wasn't well when I tried made the example sketch and have yet to plug it in and test the example. When I originally wrote it, it was for my own HID 16bit library code from 2014. So I had to whip up an example and extracted what I had into the generic joystick library... naturally it doesn't use bit arrays like I used to, so I tried something tricky with that loop... obviously forgetting that it could return 0 for neutral lol... 

Was planning to get back to that this weekend. I'm super busy with IRL stuff but I'll get to look through your posts more thoroughly after this hectic month at work. 

Would you like to submit an updated sketch and we can commit to final if you like?

**Comment by Nasty76** [comment]
not sure how that commit work but , i use that arduino to shifter and pedals so i make do something tricks whit  delayMicroseconds(10); where wait to signal settle , i allways try code stuff whitout delays cos that cause all stuff stop in arduino , i know thats not matter ur orginal purpose if that used only whit shifter but i want make realtime pedals updates , if i talk serius never see any lag cause delays but , why not make little modify cos u make all most hard work =)
i can upload that skecth stuff but i need make some adjust where i give centermode values now there are hardcoded inside code so i need make variable where there is easyly change

**Comment by Nasty76** [comment]
ok i try to put files there but not sure if that work :( at least i see them , so if u can use them good if not tell me so i try to fix problem :)

**Comment by Nasty76** [comment]
I make now pull request  charm working code but i remove analog handbrake section :(
and i change some input pins to suite better my board. so if my code not work check and douple check the input pins are setup right.
